### ISSUE TITLE
Download site not working

### ISSUE THREAD

**Issue by timos1de** [zweiler2/HoloISO_Tweaked#29]
Download site time out
![image](https://github.com/zweiler2/HoloISO_Tweaked/assets/164754528/4b3896e5-2ec2-482b-a914-0de2e5e70488)

**Comment by timos1de** [comment]
on phone site are not reachable

**Comment by Ew4n1011** [comment]
Hey server maintainer here,

Yeah it's actually been down for a while now, the proxy on the server has updated to a new major version, so I'm having to update my configuration to suit this version as well. I have let florian know beforehand.

Sorry for the downtime, I'll try and get it back up as soon as possible.

**Comment by timos1de** [comment]
ok
